name: generate-site
on:
  push:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: "Checkout Code"
      - run: ./blog_gen
        name: "Run Blog Generator"
      - name: Commit files
        run: |
          git add -f public
          git commit -m "Generate Site Files (Github Actions)"
          git subtree push --prefix public origin gh-pages

