name: generate-site
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Code"
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          git clone https://github.com/AmitPr/blog_gen.git
          python -m pip install --upgrade pip
          if [ -f blog_gen/requirements.txt ]; then pip install -r blog_gen/requirements.txt; fi
      - name: "Run Blog Generator"
        run: |
          python3 blog_gen/main.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f public
          git commit -m "Generate Site Files (Github Actions)"
          git push origin `git subtree split --prefix public master`:gh-pages --force